# DesktopSplitter build script.
# Builds everything that the installed toolchain supports:
#   - compositor (dscomp.exe)        : VS C++ (v143+)
#   - installer/devcreate            : VS C++ (v143+)
#   - installer/edid-override        : VS C++ (v143+)
#   - app (DesktopSplitter.exe)      : .NET SDK 8+
#   - driver (DesktopSplitterVdd)    : only if the WDK is installed
#   - installer/setup                : only if the signed driver package exists
#
# VERSIONING
#   The root VERSION file is the single source of truth. PATCH auto-increments
#   on every SUCCESSFUL build; MAJOR/MINOR are only ever changed by hand (use
#   -SetVersion). The new version is generated into build\generated\ BEFORE
#   anything compiles, and VERSION is only rewritten once the build succeeds -
#   so a failed build never burns or half-writes a version.
param(
    [ValidateSet('Debug', 'Release')] [string]$Configuration = 'Release',

    # Build with the current version; do not increment or write VERSION.
    # CI uses this so automated builds never push the version forward.
    [switch]$NoVersionBump,

    # Explicit override, e.g. -SetVersion 0.6.0 when bumping the minor.
    # Written back to VERSION on success (unless -NoVersionBump is also given).
    [string]$SetVersion
)
$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot

# ---------------------------------------------------------------- versioning
$versionFile = Join-Path $root 'VERSION'
$generatedDir = Join-Path $root 'build\generated'

function Read-VersionFile([string] $Path) {
    if (-not (Test-Path $Path)) { throw "VERSION file not found at $Path" }
    # Last non-empty, non-comment line wins.
    $line = Get-Content $Path |
        Where-Object { $_.Trim() -ne '' -and -not $_.TrimStart().StartsWith('#') } |
        Select-Object -Last 1
    if (-not $line) { throw "VERSION file $Path contains no version line" }
    $text = $line.Trim()
    if ($text -notmatch '^\d+\.\d+\.\d+$') {
        throw "VERSION file contains '$text', expected MAJOR.MINOR.PATCH"
    }
    return $text
}

$currentVersion = Read-VersionFile $versionFile
$writeBack = $false

if ($SetVersion) {
    if ($SetVersion -notmatch '^\d+\.\d+\.\d+$') {
        throw "-SetVersion '$SetVersion' is not MAJOR.MINOR.PATCH"
    }
    $version = $SetVersion
    $writeBack = -not $NoVersionBump
    Write-Host "Version: $currentVersion -> $version (explicit -SetVersion)" -ForegroundColor Yellow
} elseif ($NoVersionBump) {
    $version = $currentVersion
    Write-Host "Version: $version (-NoVersionBump, not incrementing)" -ForegroundColor Yellow
} else {
    $parts = $currentVersion.Split('.')
    $version = "{0}.{1}.{2}" -f $parts[0], $parts[1], ([int]$parts[2] + 1)
    $writeBack = $true
    Write-Host "Version: $currentVersion -> $version (PATCH auto-increment)" -ForegroundColor Yellow
}

$v = $version.Split('.')
$vMajor, $vMinor, $vPatch = [int]$v[0], [int]$v[1], [int]$v[2]

# Generate the version artefacts BEFORE compiling so every project picks them up.
New-Item -ItemType Directory -Path $generatedDir -Force | Out-Null

# Windows PowerShell's -Encoding UTF8 emits a BOM, which rc.exe dislikes in an
# included header and which would survive .Trim() when CI parses version.txt.
# Everything generated here is ASCII, so write it BOM-free.
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
function Write-Generated([string] $Path, [string] $Content, [switch] $NoTrailingNewline) {
    # rc.exe fails with RC1004 "unexpected end of file" on an included header
    # that does not end in a newline, so text files get one by default.
    if (-not $NoTrailingNewline -and -not $Content.EndsWith("`n")) { $Content += "`r`n" }
    [System.IO.File]::WriteAllText($Path, $Content, $utf8NoBom)
}

# .NET: imported by the root Directory.Build.props (guarded to .csproj).
@"
<?xml version="1.0" encoding="utf-8"?>
<!-- GENERATED by build.ps1 from the root VERSION file. Do not edit. -->
<Project>
  <PropertyGroup>
    <DeskSplitVersion>$version</DeskSplitVersion>
    <DeskSplitVersionMajor>$vMajor</DeskSplitVersionMajor>
    <DeskSplitVersionMinor>$vMinor</DeskSplitVersionMinor>
    <DeskSplitVersionPatch>$vPatch</DeskSplitVersionPatch>
  </PropertyGroup>
</Project>
"@ | ForEach-Object { Write-Generated (Join-Path $generatedDir 'Version.props') $_ }

# C++: plain #defines only, so this is includable from both .cpp and .rc.
@"
/* GENERATED by build.ps1 from the root VERSION file. Do not edit. */
#ifndef DESKSPLIT_VERSION_H
#define DESKSPLIT_VERSION_H

#define DS_VERSION_MAJOR $vMajor
#define DS_VERSION_MINOR $vMinor
#define DS_VERSION_PATCH $vPatch

#define DS_VERSION_STR   "$version"
#define DS_VERSION_WSTR  L"$version"

/* For VERSIONINFO FILEVERSION / PRODUCTVERSION (4 parts). */
#define DS_VERSION_COMMA $vMajor,$vMinor,$vPatch,0
#define DS_VERSION_STR4  "$version.0"

#endif /* DESKSPLIT_VERSION_H */
"@ | ForEach-Object { Write-Generated (Join-Path $generatedDir 'Version.h') $_ }

# Plain text, for scripts and CI that just want the number.
Write-Generated (Join-Path $generatedDir 'version.txt') $version -NoTrailingNewline

# GitHub Actions step output, when running in CI.
if ($env:GITHUB_OUTPUT) { "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding UTF8 }

Write-Host "  generated build\generated\{Version.props, Version.h, version.txt}"

$vswhere = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
if (-not (Test-Path $vswhere)) { throw "vswhere.exe not found - install Visual Studio 2022+" }
# Use 64-bit MSBuild: the WDK's InfVerif step ships no x86 binary and fails under 32-bit MSBuild.
$msbuild = & $vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\amd64\MSBuild.exe | Select-Object -First 1
if (-not $msbuild) { $msbuild = & $vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe | Select-Object -First 1 }
if (-not $msbuild) { throw "MSBuild not found" }

Write-Host "== compositor (dscomp) ==" -ForegroundColor Cyan
& $msbuild "$root\compositor\dscomp.vcxproj" /p:Configuration=$Configuration /p:Platform=x64 /v:m /nologo
if ($LASTEXITCODE -ne 0) { throw "compositor build failed" }

Write-Host "== installer/devcreate ==" -ForegroundColor Cyan
& $msbuild "$root\installer\devcreate\devcreate.vcxproj" /p:Configuration=$Configuration /p:Platform=x64 /v:m /nologo
if ($LASTEXITCODE -ne 0) { throw "devcreate build failed" }

# Must build before the installer: its exe is embedded by the setup stage step.
Write-Host "== installer/edid-override ==" -ForegroundColor Cyan
& $msbuild "$root\installer\edid-override\edidoverride.vcxproj" /p:Configuration=$Configuration /p:Platform=x64 /v:m /nologo
if ($LASTEXITCODE -ne 0) { throw "edidoverride build failed" }

Write-Host "== app (DesktopSplitter) ==" -ForegroundColor Cyan
dotnet build "$root\app\DesktopSplitter.csproj" -c $Configuration --nologo
if ($LASTEXITCODE -ne 0) { throw "app build failed" }

# Driver: needs the WDK (IddCx headers + WindowsUserModeDriver toolset)
$wdkFound = Get-ChildItem "${env:ProgramFiles(x86)}\Windows Kits\10\Include\*\um\iddcx\*\IddCx.h" -ErrorAction SilentlyContinue
if ($wdkFound) {
    Write-Host "== driver (DesktopSplitterVdd) ==" -ForegroundColor Cyan
    # Inf2CatUseLocalTime: stampinf writes the local date into DriverVer but inf2cat
    # validates against UTC; near midnight (UTC behind local) that reads as "postdated".
    & $msbuild "$root\driver\DesktopSplitterVdd.vcxproj" /p:Configuration=$Configuration /p:Platform=x64 /p:Inf2CatUseLocalTime=true /v:m /nologo
    if ($LASTEXITCODE -ne 0) { throw "driver build failed" }
} else {
    Write-Warning "WDK not installed - skipping driver build. See docs\BUILDING.md (winget install Microsoft.WindowsWDK.10.0.26100)"
}

# End-user installer. It embeds the SIGNED driver package plus the product
# files (the app published self-contained, the compositor and devcreate), so it
# can only be built once the driver package exists. It always embeds the Release
# artefacts - that is what ships - independently of $Configuration.
#
# The app publish happens inside the project's staging step
# (installer\setup\stage-payload.ps1), which fails the build with an actionable
# message if anything it needs is missing.
$setupBuilt = $false
$pkgDir = Join-Path $root 'driver\x64\Release\DesktopSplitterVdd'
$pkgFiles = @('DesktopSplitterVdd.inf', 'DesktopSplitterVdd.dll', 'desktopsplittervdd.cat')
$pkgMissing = $pkgFiles | Where-Object { -not (Test-Path (Join-Path $pkgDir $_)) }

if ($pkgMissing) {
    Write-Warning ("No complete driver package at driver\x64\Release\DesktopSplitterVdd " +
                   "(missing: $($pkgMissing -join ', ')) - skipping DesktopSplitterSetup.")
    Write-Warning "  Build the driver Release|x64 first; sign it with installer\sign-dev.ps1 if needed."
} else {
    Write-Host "== installer/setup (DesktopSplitterSetup) ==" -ForegroundColor Cyan
    Write-Host "   (publishes the app self-contained and embeds ~140 MB of payload - this is slow)"
    & $msbuild "$root\installer\setup\DesktopSplitterSetup.vcxproj" /p:Configuration=$Configuration /p:Platform=x64 /v:m /nologo
    if ($LASTEXITCODE -ne 0) { throw "setup build failed" }
    $setupBuilt = $true
}

# ------------------------------------------------------------ commit version
# Only now, with every project built, is the version considered consumed.
# Written via a temp file + move so an interrupted write can never leave a
# half-updated VERSION behind.
if ($writeBack) {
    $header = Get-Content $versionFile |
        Where-Object { $_.Trim() -eq '' -or $_.TrimStart().StartsWith('#') }
    $tmp = "$versionFile.tmp"
    Write-Generated $tmp (($header + $version) -join "`r`n")
    Move-Item -LiteralPath $tmp -Destination $versionFile -Force
    Write-Host "`nVERSION updated to $version" -ForegroundColor Yellow
} else {
    Write-Host "`nVERSION left at $currentVersion (not bumped)" -ForegroundColor Yellow
}

Write-Host "`nBuild complete ($Configuration) - version $version." -ForegroundColor Green
Write-Host "  compositor : compositor\build\x64\$Configuration\dscomp.exe"
Write-Host "  devcreate  : installer\devcreate\bin\x64\$Configuration\devcreate.exe"
Write-Host "  edidoverr. : installer\edid-override\build\x64\$Configuration\edidoverride.exe"

# The app's target framework moves (net8.0-windows -> net8.0-windows10.0.19041.0
# for WinRT), so resolve the real output rather than hardcoding a TFM.
$appExe = Get-ChildItem -Path (Join-Path $root "app\bin\$Configuration") -Filter 'DesktopSplitter.exe' `
    -Recurse -File -ErrorAction SilentlyContinue |
    Sort-Object LastWriteTime -Descending | Select-Object -First 1
if ($appExe) {
    Write-Host ("  app        : " + $appExe.FullName.Substring($root.Length + 1))
} else {
    Write-Host "  app        : app\bin\$Configuration\<tfm>\DesktopSplitter.exe"
}
if ($setupBuilt) {
    Write-Host "  setup      : installer\setup\bin\x64\$Configuration\DesktopSplitterSetup.exe" -ForegroundColor Green
    Write-Host "               ^ this single file is what you give an end user."
}
