// Main.cpp - dscomp: DesktopSplitter compositor.
//
// Captures each virtual monitor with DXGI Desktop Duplication and composites
// them into their segment rects on a borderless topmost window that covers the
// physical monitor.

#include "Common.h"

#include <winioctl.h>       // CTL_CODE, needed by DeskSplitProtocol.h
#include <DeskSplitProtocol.h>
#include <Version.h>        // generated by build.ps1 from the root VERSION file

#include "Log.h"
#include "Config.h"
#include "MonitorUtil.h"
#include "Renderer.h"
#include "Capture.h"
#include "CursorConfine.h"
#include "WindowRescuer.h"
#include "SessionWatcher.h"
#include "TaskbarControl.h"
#include "SegmentShared.h"

#include <shellapi.h>
#include <memory>
#include <thread>
#include <cstdio>

namespace ds {

namespace {

constexpr wchar_t kWindowClass[] = L"DeskSplitCompositorWindow";
constexpr wchar_t kWindowTitle[] = L"DesktopSplitter Compositor";
constexpr UINT_PTR kTimerId = 1;
constexpr UINT     kTimerPeriodMs = 2000;

struct Options {
    bool         verbose = false;
    bool         confine = true;      // --no-confine
    bool         rescue = true;       // --no-rescue
    bool         specialized = false; // --specialized / HidePhysicalDisplay=1
    int          waitForTarget = 0;   // --wait-for-target <seconds>, 0 = off
    int          frameDeadline = 20;  // --frame-deadline <seconds>
    bool         testPattern = false; // --test-pattern
    bool         taskbarControl = true; // --no-taskbar-control
    bool         lowestMode = false;  // --lowest-mode
    uint32_t     modeWidth = 0;       // --mode WxH@Hz
    uint32_t     modeHeight = 0;
    double       modeHz = 0.0;
    std::wstring configPath;
};

// The GUI installer writes HKLM\SOFTWARE\DesktopSplitter\HidePhysicalDisplay=1
// when the user opts into truly hiding the physical monitor.
bool HidePhysicalDisplayFlag() {
    HKEY key = nullptr;
    if (::RegOpenKeyExW(HKEY_LOCAL_MACHINE, L"SOFTWARE\\DesktopSplitter", 0,
                        KEY_READ, &key) != ERROR_SUCCESS) {
        return false;
    }
    DWORD value = 0;
    DWORD cb = sizeof(value);
    DWORD type = 0;
    const LONG r = ::RegQueryValueExW(key, L"HidePhysicalDisplay", nullptr, &type,
                                      reinterpret_cast<LPBYTE>(&value), &cb);
    ::RegCloseKey(key);
    return r == ERROR_SUCCESS && type == REG_DWORD && value != 0;
}

struct App {
    Options                                      opt;
    AppConfig                                    config;
    HWND                                         hwnd = nullptr;
    RECT                                         physicalRect = {};
    Renderer                                     renderer;
    std::vector<SegmentShared>                   segments;
    std::vector<std::unique_ptr<SegmentCapture>> captures;
    CursorConfiner                               confiner;
    SessionWatcher                               session;
    TaskbarControl                               taskbars;
    bool                                         specialized = false;
    WindowRescuer                                rescuer;

    HANDLE      stopEvent = nullptr;      // DESKSPLIT_COMPOSITOR_STOP_EVENT
    HANDLE      quitWatcher = nullptr;    // signals the watcher thread to exit
    std::thread watcherThread;
};

App* g_app = nullptr;

BOOL WINAPI ConsoleCtrlHandler(DWORD type) {
    if (type == CTRL_C_EVENT || type == CTRL_BREAK_EVENT ||
        type == CTRL_CLOSE_EVENT || type == CTRL_SHUTDOWN_EVENT ||
        type == CTRL_LOGOFF_EVENT) {
        if (g_app && g_app->hwnd) {
            ::PostMessageW(g_app->hwnd, WM_CLOSE, 0, 0);
            return TRUE;
        }
    }
    return FALSE;
}

void ApplyWindowPlacement(App& app) {
    const int x = app.physicalRect.left;
    const int y = app.physicalRect.top;
    const int w = app.physicalRect.right - app.physicalRect.left;
    const int h = app.physicalRect.bottom - app.physicalRect.top;
    ::SetWindowPos(app.hwnd, HWND_TOPMOST, x, y, w, h,
                   SWP_NOACTIVATE | SWP_SHOWWINDOW);
}

void OnDisplayChange(App& app) {
    RECT r = {};
    if (FindMonitorRect(app.config.physicalDevice, r)) {
        app.physicalRect = r;
        ApplyWindowPlacement(app);
        const UINT w = static_cast<UINT>(r.right - r.left);
        const UINT h = static_cast<UINT>(r.bottom - r.top);
        app.renderer.RequestResize(w, h);
        DS_LOG(L"display change: physical monitor is now (%ld,%ld)-(%ld,%ld)",
               r.left, r.top, r.right, r.bottom);
    } else {
        DS_WARN(L"display change: physical device '%s' is gone",
                app.config.physicalDevice.c_str());
    }
    // Making a virtual monitor primary re-bases virtual-desktop coordinates, so
    // every cached rect (including negative-coordinate ones) has to be redone.
    if (app.opt.confine) app.confiner.Refresh();
    if (app.opt.rescue) app.rescuer.OnDisplayChange();
    app.taskbars.Enforce();
}

// Hide the compositor so the physical monitor shows whatever Windows is
// actually rendering, and drop the cursor clip so the user can reach the real
// dialog. Reverse both on resume.
void OnSuspendStateChanged(void* context, bool suspended, SuspendReason why) {
    App* app = static_cast<App*>(context);
    if (!app || !app->hwnd) return;

    if (suspended) {
        if (app->opt.confine) app->confiner.Release();
        // Nothing of ours is on screen while suspended, so put every taskbar
        // back; Enforce() re-hides them on resume.
        app->taskbars.RestoreAll();
        if (!app->specialized) ::ShowWindow(app->hwnd, SW_HIDE);
        DS_LOG(L"suspend: compositor hidden, cursor clip released (%s)",
               SuspendReasonName(why));
    } else {
        if (!app->specialized) {
            ::ShowWindow(app->hwnd, SW_SHOWNOACTIVATE);
            ApplyWindowPlacement(*app);
        }
        if (app->opt.confine) {
            app->confiner.Configure(app->config.physicalDevice);
            app->confiner.InstallHook();
        }
        app->taskbars.Enforce();
        DS_LOG(L"resume: compositor shown, cursor confinement re-armed");
    }
}

LRESULT CALLBACK WndProc(HWND hwnd, UINT msg, WPARAM wParam, LPARAM lParam) {
    App* app = g_app;
    switch (msg) {
    case WM_WTSSESSION_CHANGE:
        if (app && app->session.OnSessionChange(wParam)) return 0;
        break;

    case WM_HOTKEY:
        if (app && app->session.OnHotkey(wParam)) return 0;
        break;

    case WM_MOUSEACTIVATE:
        return MA_NOACTIVATE;

    case WM_SETCURSOR:
        ::SetCursor(nullptr);   // the composited cursor is drawn by the renderer
        return TRUE;

    case WM_ERASEBKGND:
        return 1;

    case WM_DISPLAYCHANGE:
        if (app) OnDisplayChange(*app);
        return 0;

    case WM_TIMER:
        if (wParam == kTimerId && app) {
            // Backstop for EVENT_SYSTEM_DESKTOPSWITCH, which is not fully
            // reliable; this catches anything the hook missed.
            app->session.PollInputDesktop();
            if (app->session.IsSuspended()) return 0;   // stay out of the way
            app->taskbars.Enforce();
            if (app->opt.confine) app->confiner.Reapply();
            ::SetWindowPos(hwnd, HWND_TOPMOST, 0, 0, 0, 0,
                           SWP_NOMOVE | SWP_NOSIZE | SWP_NOACTIVATE);
        }
        return 0;

    case WM_CLOSE:
        DS_LOG(L"WM_CLOSE received, shutting down");
        ::DestroyWindow(hwnd);
        return 0;

    case WM_DESTROY:
        ::PostQuitMessage(0);
        return 0;

    default:
        // TaskbarCreated is a registered broadcast, so its id is not a
        // compile-time constant and cannot be a case label. Explorer sends it
        // after recreating its taskbars, which is exactly when our hiding has
        // just been undone.
        if (app && app->taskbars.IsTaskbarCreatedMessage(msg)) {
            DS_LOG(L"taskbar: Explorer recreated its taskbars - re-applying");
            app->taskbars.Enforce();
            return 0;
        }
        break;
    }
    return ::DefWindowProcW(hwnd, msg, wParam, lParam);
}

// In specialized mode the compositor still needs a window to pump messages
// (timers, WM_DISPLAYCHANGE, the stop event's PostMessage) but must never put
// pixels anywhere: the composite goes straight to the acquired display. A
// message-only window is invisible and belongs to no monitor.
bool CreateCompositorWindow(App& app, HINSTANCE hinst, bool messageOnly) {
    WNDCLASSEXW wc = {};
    wc.cbSize = sizeof(wc);
    wc.style = CS_HREDRAW | CS_VREDRAW;
    wc.lpfnWndProc = WndProc;
    wc.hInstance = hinst;
    wc.hCursor = nullptr;
    wc.hbrBackground = static_cast<HBRUSH>(::GetStockObject(BLACK_BRUSH));
    wc.lpszClassName = kWindowClass;
    if (!::RegisterClassExW(&wc)) {
        DS_ERR(L"RegisterClassEx failed: %s",
               HrString(HRESULT_FROM_WIN32(::GetLastError())));
        return false;
    }

    const int x = app.physicalRect.left;
    const int y = app.physicalRect.top;
    const int w = app.physicalRect.right - app.physicalRect.left;
    const int h = app.physicalRect.bottom - app.physicalRect.top;

    if (messageOnly) {
        app.hwnd = ::CreateWindowExW(0, kWindowClass, kWindowTitle, 0, 0, 0, 0, 0,
                                     HWND_MESSAGE, nullptr, hinst, nullptr);
        if (!app.hwnd) {
            DS_ERR(L"CreateWindowEx(message-only) failed: %s",
                   HrString(HRESULT_FROM_WIN32(::GetLastError())));
            return false;
        }
        DS_LOG(L"message-only window created (specialized mode: nothing is drawn "
               L"to the desktop)");
        return true;
    }

    app.hwnd = ::CreateWindowExW(
        WS_EX_NOACTIVATE | WS_EX_TOOLWINDOW | WS_EX_TOPMOST,
        kWindowClass, kWindowTitle, WS_POPUP,
        x, y, w, h, nullptr, nullptr, hinst, nullptr);
    if (!app.hwnd) {
        DS_ERR(L"CreateWindowEx failed: %s",
               HrString(HRESULT_FROM_WIN32(::GetLastError())));
        return false;
    }

    ::ShowWindow(app.hwnd, SW_SHOWNOACTIVATE);
    ApplyWindowPlacement(app);
    DS_LOG(L"window created at (%d,%d) %dx%d", x, y, w, h);
    return true;
}

HANDLE OpenOrCreateStopEvent() {
    HANDLE h = ::OpenEventW(SYNCHRONIZE, FALSE, DESKSPLIT_COMPOSITOR_STOP_EVENT);
    if (h) {
        DS_VERB(L"opened existing stop event");
        return h;
    }
    h = ::CreateEventW(nullptr, TRUE, FALSE, DESKSPLIT_COMPOSITOR_STOP_EVENT);
    if (h) {
        DS_VERB(L"created stop event");
        return h;
    }
    DS_WARN(L"cannot open or create '%s': %s (use WM_CLOSE or Ctrl+C to stop)",
            DESKSPLIT_COMPOSITOR_STOP_EVENT,
            HrString(HRESULT_FROM_WIN32(::GetLastError())));
    return nullptr;
}

void StartStopWatcher(App& app) {
    app.stopEvent = OpenOrCreateStopEvent();
    if (!app.stopEvent) return;

    app.quitWatcher = ::CreateEventW(nullptr, TRUE, FALSE, nullptr);
    if (!app.quitWatcher) return;

    App* a = &app;
    app.watcherThread = std::thread([a] {
        ::SetThreadDescription(::GetCurrentThread(), L"dscomp-stopwatch");
        HANDLE handles[2] = { a->stopEvent, a->quitWatcher };
        const DWORD r = ::WaitForMultipleObjects(2, handles, FALSE, INFINITE);
        if (r == WAIT_OBJECT_0) {
            DS_LOG(L"stop event signalled");
            if (a->hwnd) ::PostMessageW(a->hwnd, WM_CLOSE, 0, 0);
        }
    });
}

void StopWatcher(App& app) {
    if (app.quitWatcher) ::SetEvent(app.quitWatcher);
    if (app.watcherThread.joinable()) app.watcherThread.join();
    if (app.quitWatcher) { ::CloseHandle(app.quitWatcher); app.quitWatcher = nullptr; }
    if (app.stopEvent)   { ::CloseHandle(app.stopEvent);   app.stopEvent = nullptr; }
}

void PrintUsage() {
    ::fwprintf(stderr,
               L"dscomp - DesktopSplitter compositor\n"
               L"\n"
               L"Usage: dscomp.exe [--verbose] [--config <path>] [--no-confine]\n"
               L"                  [--no-rescue] [--specialized]\n"
               L"\n"
               L"  --verbose, -v    Verbose logging to stderr / OutputDebugString.\n"
               L"  --config <path>  Override %%ProgramData%%\\DesktopSplitter\\config.json.\n"
               L"  --no-confine     Do not keep the cursor off the covered monitor.\n"
               L"  --no-rescue      Do not relocate windows that open behind the\n"
               L"                   compositor onto the first virtual monitor.\n"
               L"  --lowest-mode    Select the SMALLEST advertised mode instead of the\n"
               L"                   largest. Diagnostic: distinguishes a bandwidth/DSC\n"
               L"                   problem from an API-usage problem.\n"
               L"  --mode WxH@Hz    Select an explicit mode, e.g. 1920x1080@60.\n"
               L"  --no-taskbar-control\n"
               L"                   Do not enforce per-segment taskbar visibility;\n"
               L"                   leave every taskbar exactly as Windows put it.\n"
               L"  --test-pattern   Draw a cycling solid colour instead of the captured\n"
               L"                   segments, with NO capture threads. Proves the\n"
               L"                   presentation path in isolation. Use this FIRST when\n"
               L"                   the specialized display comes up black.\n"
               L"  --wait-for-target <s>\n"
               L"                   Implies --specialized. Wait up to <s> seconds for\n"
               L"                   the display to be removed from the desktop and\n"
               L"                   acquire it the instant it is. START DSCOMP FIRST,\n"
               L"                   THEN TOGGLE: the display goes black when it leaves\n"
               L"                   the desktop, and this makes that a blink rather\n"
               L"                   than a dark screen. Falls back to the window path\n"
               L"                   if the wait expires.\n"
               L"  --frame-deadline <s>\n"
               L"                   Acquired but no frame scanned out within <s>\n"
               L"                   seconds means a black panel: release and exit 20.\n"
               L"                   Default 20.\n"
               L"  --specialized    Drive the physical monitor directly through\n"
               L"                   Windows.Devices.Display.Core, removing it from the\n"
               L"                   desktop entirely. Needs the monitor marked as a\n"
               L"                   specialized display (see docs/HIDING.md); falls back\n"
               L"                   to the window path otherwise. Also enabled by HKLM\\\n"
               L"                   SOFTWARE\\DesktopSplitter HidePhysicalDisplay=1.\n"
               L"  --help, -h       Show this message.\n"
               L"\n"
               L"Stops on the named event %s, WM_CLOSE, or Ctrl+C.\n",
               DESKSPLIT_COMPOSITOR_STOP_EVENT);
}

int Run(HINSTANCE hinst, const Options& opt) {
    LogInit(opt.verbose);
    DS_LOG(L"dscomp " DS_VERSION_WSTR L" starting");

    App app;
    app.opt = opt;
    g_app = &app;

    if (!LoadConfig(opt.configPath, app.config)) {
        DS_ERR(L"failed to load config from '%s'", opt.configPath.c_str());
        return exitcode::kConfigFailed;
    }

    if (!FindMonitorRect(app.config.physicalDevice, app.physicalRect)) {
        DS_ERR(L"physical monitor '%s' not found", app.config.physicalDevice.c_str());
        if (opt.specialized) {
            DS_ERR(L"  dscomp must be started BEFORE the display is removed from "
                   L"the desktop - once specialized it can no longer be resolved "
                   L"by GDI device name. Re-attach it, start dscomp with "
                   L"--wait-for-target, then toggle.");
        }
        return exitcode::kMonitorNotFound;
    }
    DS_LOG(L"physical monitor '%s' at (%ld,%ld)-(%ld,%ld)",
           app.config.physicalDevice.c_str(), app.physicalRect.left,
           app.physicalRect.top, app.physicalRect.right, app.physicalRect.bottom);

    app.segments = std::vector<SegmentShared>(app.config.segments.size());

    // 1. Device first - it needs no window.
    if (!app.renderer.InitDevice(app.config, &app.segments)) {
        DS_ERR(L"renderer device initialisation failed");
        return exitcode::kRendererFailed;
    }

    // 2. Decide the presenter BEFORE any window exists. With --wait-for-target
    //    this blocks until the user removes the display from the desktop, so
    //    the compositor is already waiting and acquires it immediately.
    app.renderer.SetModeOverride(opt.lowestMode, opt.modeWidth, opt.modeHeight,
                                 opt.modeHz);
    const PresenterKind kind =
        app.renderer.DecidePresenter(opt.specialized, opt.waitForTarget,
                                     opt.frameDeadline);
    const bool specializedActive = (kind == PresenterKind::Specialized);

    // 3. Now create the right kind of window and bind the presenter to it.
    if (!CreateCompositorWindow(app, hinst, specializedActive)) {
        return exitcode::kWindowFailed;
    }
    if (!app.renderer.FinishInit(app.hwnd)) {
        DS_ERR(L"renderer initialisation failed");
        ::DestroyWindow(app.hwnd);
        return exitcode::kRendererFailed;
    }

    if (app.opt.testPattern) {
        DS_LOG(L"--test-pattern: drawing a cycling solid colour, NO capture "
               L"threads. If the panel shows shifting colour, the presentation "
               L"path works and any black screen is a capture problem.");
    }
    for (size_t i = 0; !app.opt.testPattern && i < app.config.segments.size(); ++i) {
        auto cap = std::make_unique<SegmentCapture>();
        if (!cap->Start(i, app.config.segments[i], app.renderer.Gpu(),
                        &app.segments[i])) {
            DS_ERR(L"failed to start capture for segment %zu", i);
        } else {
            app.captures.push_back(std::move(cap));
        }
    }

    // In specialized mode the physical monitor is not part of the desktop at
    // all, so there is nothing to confine the cursor away from and no window can
    // land behind the compositor. Both helpers are pointless there.
    if (specializedActive) {
        DS_LOG(L"specialized presentation active: skipping cursor confinement "
               L"and the window rescuer (the display is out of the desktop)");
    }

    if (app.opt.confine && !specializedActive) {
        app.confiner.Configure(app.config.physicalDevice);
        if (!app.confiner.InstallHook()) {
            // Exclusion is hook-only, so no hook means no confinement. Carry on
            // rather than degrading cursor movement with a bad ClipCursor.
            DS_WARN(L"running without cursor confinement");
        }
    } else if (!specializedActive) {
        DS_LOG(L"cursor confinement disabled (--no-confine)");
    }

    if (app.opt.rescue && !specializedActive) {
        // Segment 1 is the relocation target: config segments[0].
        // launchSegment is optional and independent of which segment is
        // primary; out-of-range values disable it rather than guessing.
        std::wstring launchDevice;
        const int ls = app.config.launchSegment;
        if (ls >= 0 && static_cast<size_t>(ls) < app.config.segments.size()) {
            launchDevice = app.config.segments[static_cast<size_t>(ls)].virtualDevice;
            DS_LOG(L"new app windows will open on segment %d (%s)", ls,
                   launchDevice.c_str());
        } else if (ls >= 0) {
            DS_WARN(L"launchSegment %d is out of range (%zu segment(s)) - ignoring",
                    ls, app.config.segments.size());
        }
        app.rescuer.Start(app.config.physicalDevice,
                          app.config.segments[0].virtualDevice, launchDevice);
    } else if (!specializedActive) {
        DS_LOG(L"window rescuer disabled (--no-rescue)");
    }

    app.renderer.SetTestPattern(opt.testPattern);
    app.specialized = specializedActive;
    if (opt.taskbarControl && !specializedActive) {
        app.taskbars.Start(app.hwnd, app.config);
    } else if (!opt.taskbarControl) {
        DS_LOG(L"taskbar control disabled (--no-taskbar-control)");
    }
    app.session.Start(app.hwnd, OnSuspendStateChanged, &app);

    ::SetTimer(app.hwnd, kTimerId, kTimerPeriodMs, nullptr);
    StartStopWatcher(app);
    app.renderer.StartThread();
    DS_LOG(L"running");

    MSG msg = {};
    while (::GetMessageW(&msg, nullptr, 0, 0) > 0) {
        ::TranslateMessage(&msg);
        ::DispatchMessageW(&msg);
    }

    DS_LOG(L"shutting down");
    ::KillTimer(app.hwnd, kTimerId);
    app.taskbars.Stop();     // restores anything we hid, on every exit path
    app.session.Stop();
    app.rescuer.Stop();
    app.renderer.StopThread();
    // Read only after the render thread has joined, so the flag it may set on
    // its very last iteration cannot be missed.
    const bool fatal = app.renderer.FatalRuntimeError();
    for (auto& c : app.captures) c->Stop();
    app.captures.clear();
    app.renderer.Shutdown();
    app.confiner.Release();
    StopWatcher(app);
    app.segments.clear();
    g_app = nullptr;

    ::UnregisterClassW(kWindowClass, hinst);

    const int rc = ExitCodeForRun(fatal);
    if (rc != exitcode::kOk) {
        DS_ERR(L"dscomp exiting with code %d: the display was lost while "
               L"presenting", rc);
    } else {
        DS_LOG(L"dscomp exited");
    }
    return rc;
}

} // namespace
} // namespace ds

int APIENTRY wWinMain(_In_ HINSTANCE hInstance, _In_opt_ HINSTANCE, _In_ LPWSTR,
                      _In_ int) {
    // Inherit the launching console (if any) so stderr logging and Ctrl+C work.
    // Only redirect stderr to the console when it was not already redirected by
    // the caller (e.g. "dscomp.exe 2> log.txt"), otherwise we would clobber it.
    {
        const HANDLE herr = ::GetStdHandle(STD_ERROR_HANDLE);
        const bool haveStdErr = (herr != nullptr && herr != INVALID_HANDLE_VALUE);
        if (::AttachConsole(ATTACH_PARENT_PROCESS) && !haveStdErr) {
            FILE* f = nullptr;
            ::freopen_s(&f, "CONOUT$", "w", stderr);
        }
    }
    ::SetConsoleCtrlHandler(ds::ConsoleCtrlHandler, TRUE);
    ::SetProcessDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE_V2);

    ds::Options opt;
    opt.configPath = ds::DefaultConfigPath();
    opt.specialized = ds::HidePhysicalDisplayFlag();

    int argc = 0;
    LPWSTR* argv = ::CommandLineToArgvW(::GetCommandLineW(), &argc);
    if (argv) {
        for (int i = 1; i < argc; ++i) {
            const std::wstring a = argv[i];
            if (a == L"--verbose" || a == L"-v") {
                opt.verbose = true;
            } else if ((a == L"--config" || a == L"-c") && i + 1 < argc) {
                opt.configPath = argv[++i];
            } else if (a == L"--no-confine") {
                opt.confine = false;
            } else if (a == L"--no-rescue") {
                opt.rescue = false;
            } else if (a == L"--specialized") {
                opt.specialized = true;
            } else if (a == L"--wait-for-target" && i + 1 < argc) {
                opt.waitForTarget = ::_wtoi(argv[++i]);
                if (opt.waitForTarget < 0) opt.waitForTarget = 0;
                opt.specialized = true;   // waiting only makes sense there
            } else if (a == L"--test-pattern") {
                opt.testPattern = true;
            } else if (a == L"--no-taskbar-control") {
                opt.taskbarControl = false;
            } else if (a == L"--lowest-mode") {
                opt.lowestMode = true;
            } else if (a == L"--mode" && i + 1 < argc) {
                // WxH@Hz, e.g. 1920x1080@60
                const std::wstring m = argv[++i];
                if (::swscanf_s(m.c_str(), L"%ux%u@%lf", &opt.modeWidth,
                                &opt.modeHeight, &opt.modeHz) < 2) {
                    ::fwprintf(stderr, L"dscomp: --mode wants WxH@Hz, e.g. "
                                       L"1920x1080@60\n");
                    ::LocalFree(argv);
                    return ds::exitcode::kBadArgs;
                }
            } else if (a == L"--frame-deadline" && i + 1 < argc) {
                opt.frameDeadline = ::_wtoi(argv[++i]);
                if (opt.frameDeadline < 0) opt.frameDeadline = 0;
            } else if (a == L"--help" || a == L"-h" || a == L"/?") {
                ds::PrintUsage();
                ::LocalFree(argv);
                return 0;
            } else {
                ::fwprintf(stderr, L"dscomp: unknown argument '%s'\n", a.c_str());
                ds::PrintUsage();
                ::LocalFree(argv);
                return 1;
            }
        }
        ::LocalFree(argv);
    }

    const int rc = ds::Run(hInstance, opt);
    ::SetConsoleCtrlHandler(ds::ConsoleCtrlHandler, FALSE);
    return rc;
}
